export const AuthConstants = {
  JWT_ISSUER: 'JWT_ISSUER',
  JWT_ACCESS_TOKEN_SECRET: 'JWT_ACCESS_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_MS: 'JWT_ACCESS_TOKEN_EXPIRATION_MS',
  JWT_REFRESH_TOKEN_SECRET: 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRATION_MS: 'JWT_REFRESH_TOKEN_EXPIRATION_MS',
};
